import { StyleSheet, Text, View } from "react-native";
import { BackHeader } from "@/components/BackHeader";
import { Avatar, Card, EmptyState, ErrorState, LoadingState, Screen, SectionTitle } from "@/components/ui";
import { useAsyncData } from "@/hooks/useAsyncData";
import { meetingService } from "@/services/meeting";
import { colors, spacing } from "@/theme/tokens";

export default function RankingsScreen() {
  const { data, error, isLoading, reload } = useAsyncData(async () => { const meetings = await meetingService.history(); const totals = new Map<string, { name: string; appearances: number; seconds: number }>(); meetings.forEach((meeting) => meeting.speakers.forEach((speaker) => { const key = speaker.userId || speaker.email || speaker.name; const current = totals.get(key) || { name: speaker.name, appearances: 0, seconds: 0 }; current.appearances += 1; current.seconds += speaker.spokenSeconds || 0; totals.set(key, current); })); return [...totals.values()].sort((a, b) => b.appearances * 1000 + b.seconds - (a.appearances * 1000 + a.seconds)); });
  const top = (data || []).slice(0, 3); const max = Math.max(1, ...top.map((item) => item.appearances));
  return <Screen><BackHeader title="Bảng xếp hạng" subtitle="Tính từ lịch sử cuộc họp" compact />{isLoading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={reload} /> : !data?.length ? <EmptyState title="Chưa có dữ liệu" message="Bảng xếp hạng sẽ xuất hiện sau khi có dữ liệu tham dự cuộc họp." /> : <><Card><SectionTitle>Top thành viên tham dự</SectionTitle><View style={styles.columns}>{top.map((item, index) => <View key={item.name} style={styles.column}><Avatar initials={item.name.split(" ").map((part) => part[0]).slice(-2).join("").toUpperCase()} /><Text numberOfLines={1} style={styles.name}>{item.name}</Text><Text style={styles.score}>{item.appearances} buổi</Text><View style={[styles.bar, { height: 55 + item.appearances / max * 90 }]} /><Text style={styles.rank}>#{index + 1}</Text></View>)}</View></Card><Card style={styles.list}>{data.slice(3).map((item, index) => <View key={item.name} style={styles.row}><Text style={styles.rowRank}>{index + 4}</Text><View style={styles.grow}><Text style={styles.rowName}>{item.name}</Text><Text style={styles.meta}>{item.appearances} buổi · {Math.round(item.seconds / 60)} phút phát biểu</Text></View></View>)}</Card></>}</Screen>;
}
const styles = StyleSheet.create({ columns: { height: 270, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: spacing.sm }, column: { width: "30%", alignItems: "center" }, name: { width: "100%", marginTop: spacing.xs, color: colors.text, fontSize: 11, fontWeight: "800", textAlign: "center" }, score: { marginVertical: 3, color: colors.primaryDark, fontSize: 12, fontWeight: "900" }, bar: { width: "100%", borderTopLeftRadius: 10, borderTopRightRadius: 10, backgroundColor: colors.primary }, rank: { width: "100%", paddingVertical: 5, color: "#FFFFFF", backgroundColor: colors.primaryDark, fontSize: 11, fontWeight: "900", textAlign: "center" }, list: { paddingVertical: 0 }, row: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowRank: { width: 26, color: colors.muted, fontSize: 13, fontWeight: "900" }, grow: { flex: 1 }, rowName: { color: colors.text, fontSize: 14, fontWeight: "800" }, meta: { marginTop: 3, color: colors.muted, fontSize: 11 } });
