const screens = [
  ["Xác thực","login","01","Đăng nhập lần đầu","Tài khoản bắt buộc ở lần đăng nhập đầu tiên."],
  ["Xác thực","biometric","02","Cài đặt sinh trắc học","Bật Face ID hoặc vân tay sau khi xác thực tài khoản."],
  ["Điều hướng chính","home","03","Trang chủ","Tổng hợp cuộc họp, chat và thao tác nhanh."],
  ["Điều hướng chính","notifications","04","Thông báo","Deep link đến đúng cuộc họp hoặc chat."],
  ["Cuộc họp","meetings","05","Danh sách & lịch họp","Lịch tuần, trạng thái và quyền tạo cuộc họp."],
  ["Cuộc họp","meeting-detail","06","Chi tiết cuộc họp","Thông tin, người tham dự và hành động theo quyền."],
  ["Cuộc họp","meeting-checkin","07","Check-in QR/GPS","Camera, vị trí, nhập mã và trạng thái thử lại."],
  ["Cuộc họp","meeting-live","08","Điều hành trực tiếp","Bộ đếm, diễn giả, thứ tự, slide và điều khiển."],
  ["Cuộc họp / Chi tiết","meeting-interaction","09","↳ Tương tác & quay thưởng","Màn hình con chỉ mở từ Chi tiết cuộc họp."],
  ["Thành viên","members","10","Sơ đồ thành viên","Cây tổ chức có pan/zoom và chế độ danh sách."],
  ["Thành viên","member-detail","11","Hồ sơ thành viên","Hồ sơ BNI, ngành nghề, liên hệ và thị trường mục tiêu."],
  ["Cộng đồng","rankings","12","Bảng xếp hạng","Thành viên tích cực và vắng mặt theo thời gian."],
  ["Cộng đồng","chat-list","13","Danh sách trò chuyện","Chat cá nhân, nhóm, online và chưa đọc."],
  ["Cộng đồng","chat-room","14","Phòng trò chuyện","Tin nhắn, file, phản hồi, ghim và quản trị nhóm."],
  ["Tài nguyên","resources","15","Tài nguyên","Cá nhân, nhóm, Google Drive, upload và xem trước."],
  ["Hệ thống","more","16","Mục Thêm","Điểm vào module ít dùng và chức năng quản trị."],
  ["Hệ thống","admin-users","17","Quản trị người dùng","Tìm kiếm, lọc, thêm/sửa và kích hoạt tài khoản."],
  ["Hệ thống","admin-roles","18","Vai trò & phân quyền","Quyền được nhóm theo module, không dùng bảng ngang."],
  ["Hệ thống","settings","19","Cài đặt","Hồ sơ, bảo mật, sinh trắc học và cấu hình ERP."],
  ["Tablet","tablet-command","20","Tablet — bàn điều hành","Bố cục hai cột tối ưu cho điều hành họp."]
];

const navItems=[["home","⌂","Trang chủ"],["meetings","□","Cuộc họp"],["members","◇","Thành viên"],["chat-list","○","Trò chuyện"],["more","···","Thêm"]];
function nav(active){return '<nav class="bottom-nav">'+navItems.map(function(x){return '<button data-go="'+x[0]+'" class="nav-item '+(active===x[0]?'active':'')+'"><i>'+x[1]+'</i>'+x[2]+'</button>'}).join('')+'</nav>'}
function header(title,sub,acts){return '<header class="app-header"><div><h2>'+title+'</h2>'+(sub?'<small>'+sub+'</small>':'')+'</div><div class="actions">'+(acts||"").split("|").filter(Boolean).map(function(x){return '<button class="icon-btn">'+x+'</button>'}).join('')+'</div></header>'}
function avatar(t){return '<div class="avatar round">'+t+'</div>'}
function row(a,b,c,go){return '<div class="list-row" '+(go?'data-go="'+go+'"':'')+'>'+avatar(a)+'<div class="grow"><strong>'+b+'</strong><small>'+c+'</small></div><span class="chev">›</span></div>'}
function tabs(items,active){return '<div class="tabs">'+items.map(function(x){return '<button class="tab '+(x===active?'active':'')+'">'+x+'</button>'}).join('')+'</div>'}
function flow(){return '<div class="flow"><span class="active">Check-in</span><span class="active">Mở họp</span><span class="active">Phát biểu</span><span>Tương tác</span><span>Kết thúc</span></div>'}
function shell(title,sub,content,active,acts){return '<section class="screen">'+header(title,sub,acts)+'<div class="scroll stack">'+content+'</div>'+nav(active)+'</section>'}
function kpi(label,value,note){return '<div class="card kpi"><small>'+label+'</small><b>'+value+'</b><p>'+note+'</p></div>'}

function content(id){
  if(id==="login") return '<section class="screen auth"><div class="auth-logo">iG</div><h1>iGen Connect</h1><p>Kết nối và vận hành cộng đồng hiệu quả</p><div class="auth-card"><div class="form-group"><label>SỐ ĐIỆN THOẠI HOẶC EMAIL</label><input class="field" placeholder="Nhập tài khoản"></div><div class="form-group"><label>MẬT KHẨU</label><input class="field" value="••••••••"></div><div class="row between tiny"><span>□ Ghi nhớ tài khoản</span><span>Quên mật khẩu?</span></div><button data-go="home" class="primary-btn" style="width:100%;margin-top:13px">Đăng nhập</button></div><p class="tiny">Bảo mật · Điều khoản · Hỗ trợ</p></section>';

  if(id==="biometric") return shell("Bảo mật","Đăng nhập và thiết bị",'<div class="card speaker"><div class="auth-logo">◎</div><h3>Đăng nhập sinh trắc học</h3><p>Dùng Face ID hoặc vân tay. Mật khẩu luôn là phương án dự phòng.</p></div><div class="card">'+row("◎","Face ID / Vân tay","Chưa thiết lập trên thiết bị này","") + row("⌁","Yêu cầu khi mở lại app","Đang bật","")+'</div><div class="card"><h3>Quy trình bật</h3><p>1. Xác nhận mật khẩu<br>2. Xác thực sinh trắc học<br>3. Lưu khóa an toàn trên thiết bị</p></div><button class="primary-btn">Thiết lập sinh trắc học</button>',"more","‹");

  if(id==="home") return shell("Xin chào, Minh","Thứ Tư, 07 tháng 10",'<div class="card hero" data-go="meeting-live"><span class="badge red">ĐANG DIỄN RA</span><h3 style="margin-top:9px">Họp Chapter tháng 10</h3><p>48 người check-in · Người nói: Nguyễn Hoàng</p><button class="secondary-btn" style="margin-top:9px">Vào phòng họp →</button></div><div class="kpis">'+kpi("Thành viên","68","61 hoạt động")+kpi("Tỷ lệ tham dự","89%","+4% tháng này")+kpi("Cuộc họp sắp tới","02","Tuần này")+kpi("Tin chưa đọc","12","3 lượt nhắc tên")+'</div><div class="section-title"><strong>Sắp tới</strong><a data-go="meetings">Xem tất cả</a></div><div class="card">'+row("CH","Họp Chapter tháng 10","Đang diễn ra · 07:00–09:00","meeting-detail")+row("BM","Business Meeting tuần 2","14/10 · Riverside Palace","meeting-detail")+'</div><div class="menu-grid"><div class="tile" data-go="meeting-checkin"><i>QR</i><b>Check-in</b><small>Quét mã cuộc họp</small></div><div class="tile" data-go="chat-list"><i>○</i><b>Trò chuyện</b><small>Xem tin nhắn</small></div></div>',"home","⌕|♢");

  if(id==="notifications") return shell("Thông báo","8 mục chưa đọc",'<div class="notification-filters"><button class="active">Tất cả</button><button>Cuộc họp</button><button>Chat</button></div><div class="card notification-list">'+row("CH","Cuộc họp bắt đầu sau 30 phút","Business Meeting · 2 phút trước","meeting-detail")+row("@","Lan đã nhắc đến bạn","Chapter Leadership · 12 phút trước","chat-room")+'</div>',"home","✓");

  if(id==="meetings"){var dates=[28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1];var cells=dates.map(function(n,i){var outside=i<3||i===34,active=n===7&&!outside,event=[7,14,20,28].includes(n)&&!outside;return '<button class="date-cell '+(outside?'outside ':'')+(active?'active ':'')+(event?'has-event':'')+'"><span>'+n+'</span>'+(event?'<i></i>':'')+'</button>'}).join("");var month='<div class="month-calendar"><div class="month-head"><button>‹</button><strong>Tháng 10, 2026</strong><button>›</button></div><div class="weekdays"><span>T2</span><span>T3</span><span>T4</span><span>T5</span><span>T6</span><span>T7</span><span>CN</span></div><div class="month-grid">'+cells+'</div></div>';return shell("Cuộc họp","Lịch theo tháng",month+'<div class="section-title"><strong>Ngày 07/10 · 1 cuộc họp</strong><a>Hôm nay</a></div><div class="card">'+row("LIVE","Họp Chapter tháng 10","07:00–09:00 · 48 check-in","meeting-detail")+'</div>'+tabs(["Tất cả","Sắp tới","Đang họp","Đã kết thúc"],"Tất cả")+'<input class="search" placeholder="⌕  Tìm cuộc họp, địa điểm..."><div class="card">'+row("BM","Business Meeting tuần 2","14/10 · Riverside Palace","meeting-detail")+row("ĐT","Đào tạo thành viên mới","20/10 · Trực tuyến","meeting-detail")+'</div><button class="primary-btn">＋ Tạo cuộc họp</button>',"meetings","+")}

  if(id==="meeting-detail") return shell("Chi tiết cuộc họp","",'<div class="card hero"><span class="badge red">ĐANG DIỄN RA</span><h3 style="margin-top:9px">Họp Chapter tháng 10</h3><p>07:00–09:00 · Riverside Palace<br>123 Nguyễn Huệ, Quận 1</p></div>'+flow()+'<div class="kpis">'+kpi("Check-in","48","42 thành viên · 6 khách")+kpi("Đã phát biểu","17/48","Trung bình 51 giây")+'</div><div class="card">'+row("QR","Check-in cuộc họp","Quét QR hoặc xác nhận GPS","meeting-checkin")+row("▶","Phòng điều hành","Bộ đếm, diễn giả và slide","meeting-live")+row("✦","Tương tác & quay thưởng","Phản hồi, câu hỏi, người thắng","meeting-interaction")+'</div><div class="buttons"><button class="secondary-btn">Tạm dừng</button><button class="danger-btn">Kết thúc họp</button></div>',"meetings","‹|⋯");

  if(id==="meeting-checkin") return shell("Check-in","Họp Chapter tháng 10",tabs(["Quét QR","Mã cá nhân","Danh sách"],"Quét QR")+'<div class="qr">KHUNG CAMERA<br>QUÉT QR</div><div class="card row between"><div><h3>Vị trí của bạn</h3><p>Trong phạm vi 42m · Cho phép 150m</p></div><span class="badge cyan">Hợp lệ</span></div><p class="tiny" style="text-align:center">Nếu camera hoặc vị trí gặp lỗi, hiển thị nguyên nhân và nút Thử lại.</p><button class="secondary-btn">Nhập mã check-in</button>',"meetings","‹");

  if(id==="meeting-live") return shell("Điều hành cuộc họp","48 người tham dự",flow()+'<div class="card speaker">'+avatar("NH")+'<h3>Nguyễn Hoàng</h3><p>Công nghệ thông tin · Thành viên</p></div><div class="card timer"><small>THỜI GIAN CÒN LẠI</small><b>00:42</b><div class="progress"><span style="width:62%"></span></div></div><div class="buttons"><button class="secondary-btn">Ⅱ Tạm dừng</button><button class="primary-btn">Người tiếp theo ›</button></div><div class="card"><div class="section-title"><strong>Thứ tự tiếp theo</strong><a>Điều chỉnh</a></div>'+row("18","Lê Thanh","60 giây","")+row("19","Phạm Anh","45 giây","")+'</div><div class="buttons"><button class="secondary-btn">Mở slide</button><button class="danger-btn">Kết thúc họp</button></div>',"meetings","▣|⋯");

  if(id==="meeting-interaction") return shell("Tương tác & quay thưởng","Trong Chi tiết cuộc họp",'<div class="card nested-context"><span class="badge cyan">HỌP CHAPTER THÁNG 10</span><p>Đây là chức năng con của cuộc họp đang chọn, không phải module độc lập.</p></div>'+tabs(["Phản hồi","Câu hỏi","Quay thưởng"],"Phản hồi")+'<div class="kpis">'+kpi("Đã phản hồi","31","/48 người tham dự")+kpi("Câu hỏi","08","3 câu đã trả lời")+'</div><div class="card speaker"><h3>Đám mây phản hồi trực tiếp</h3><p style="font-size:15px;color:#17869a;line-height:2"><b>HỢP TÁC</b> · Kết nối · <b>CƠ HỘI</b><br>Học hỏi · <b>TRUYỀN CẢM HỨNG</b></p></div><div class="card">'+row("?","Làm thế nào để đăng ký diễn giả?","Ẩn danh · 5 lượt thích","")+'</div><button class="primary-btn">Bắt đầu quay thưởng</button>',"meetings","‹");

  if(id==="members"){var people=[["NT","Nguyễn Thành","Giám đốc Chapter","Công nghệ"],["LH","Lê Hương","Phó giám đốc","Tài chính"],["TV","Trần Vũ","Thư ký","Sự kiện"],["PM","Phạm Minh","Thành viên","Xây dựng"],["HA","Hoàng Anh","Thành viên","Marketing"],["DN","Đỗ Nam","Thành viên","Logistics"]];var cards=people.map(function(p){return '<article class="member-card" data-go="member-detail"><div class="member-cover"></div>'+avatar(p[0])+'<h3>'+p[1]+'</h3><p>'+p[2]+'</p><span class="badge cyan">'+p[3]+'</span><div class="member-actions"><button>Nhắn tin</button><button>Chi tiết</button></div></article>'}).join("");return shell("Thành viên","68 thành viên",tabs(["Thẻ thành viên","Sơ đồ tổ chức"],"Thẻ thành viên")+'<input class="search" placeholder="⌕  Tìm tên, lĩnh vực, công ty..."><div class="member-grid">'+cards+'</div><button class="secondary-btn">Mở sơ đồ tổ chức có pan/zoom</button>',"members","⌕|+")}

  if(id==="member-detail") return shell("Hồ sơ thành viên","",'<div class="card speaker">'+avatar("NT")+'<h3>Nguyễn Thành</h3><p>Giám đốc Chapter · Đang hoạt động</p><p><span class="badge cyan">Công nghệ</span> <span class="badge">TP.HCM</span></p></div><div class="buttons"><button data-go="chat-room" class="primary-btn">Nhắn tin</button><button class="secondary-btn">Gọi điện</button></div><div class="card">'+row("C","Công ty","iGen Technology","")+row("L","Lĩnh vực","Phần mềm doanh nghiệp","")+row("T","Thị trường mục tiêu","SME và cộng đồng kinh doanh","")+'</div><div class="card"><h3>Giới thiệu</h3><p>Mô tả công việc, ảnh bìa và bộ sưu tập của thành viên.</p></div>',"members","‹|⋯");


  if(id==="rankings") return shell("Bảng xếp hạng","Tháng 10/2026",tabs(["Tích cực","Vắng mặt"],"Tích cực")+'<div class="card"><div class="section-title"><strong>Top thành viên</strong><a>Điểm hoạt động</a></div><div class="rank-columns"><div class="rank-col second">'+avatar("LH")+'<b>Lê Hương</b><span>89</span><div class="rank-bar"></div><small>#2</small></div><div class="rank-col first">'+avatar("NT")+'<b>Nguyễn Thành</b><span>96</span><div class="rank-bar"></div><small>#1</small></div><div class="rank-col third">'+avatar("TV")+'<b>Trần Vũ</b><span>84</span><div class="rank-bar"></div><small>#3</small></div></div></div><div class="card">'+row("4","Phạm Minh","78 điểm · 14 lần phát biểu","")+row("5","Hoàng Anh","72 điểm · 12 lần phát biểu","")+row("6","Đỗ Nam","69 điểm · 10 lần phát biểu","")+'</div>',"more","⌕|↻");

  if(id==="chat-list") return shell("Trò chuyện","12 tin chưa đọc",'<input class="search" placeholder="⌕  Tìm cuộc trò chuyện, thành viên...">'+tabs(["Tất cả","Chưa đọc","Nhóm"],"Tất cả")+'<div class="card">'+row("CL","Chapter Leadership","Lan: @Minh xem giúp nội dung này · 8 mới","chat-room")+row("LH","Lê Hương","Cảm ơn bạn nhé · 2 mới","chat-room")+row("☁","Cloud của tôi","File kế hoạch sự kiện.pdf","chat-room")+row("TV","Trần Vũ","Hẹn gặp trong buổi họp","chat-room")+'</div>',"chat-list","♬|+");

  if(id==="chat-room") return '<section class="screen">'+header("Chapter Leadership","18 thành viên · 7 online","‹|⌕|⋯")+'<div class="scroll stack" style="background:#f1f6f8"><div class="message">Tài liệu cuộc họp tuần này đã được cập nhật.</div><div class="message mine">Mình đã xem. Phần lịch trình rất rõ rồi nhé.</div><div class="message"><b>@Minh</b> xem giúp danh sách khách mời nhé.</div><div class="card">'+row("PDF","Danh-sach-khach-moi.pdf","2,4 MB · Lan gửi","")+'</div><div class="message mine">Được, mình sẽ kiểm tra trước 10 giờ.</div></div><div class="composer"><button class="icon-btn">＋</button><input class="field" placeholder="Nhập tin nhắn..."><button class="icon-btn" style="color:#fff;background:var(--cyan)">➤</button></div>'+nav("chat-list")+'</section>';

  if(id==="resources") return shell("Tài nguyên","Không gian làm việc",tabs(["Cá nhân","Chapter","Google Drive"],"Cá nhân")+'<div class="buttons"><button class="secondary-btn">＋ Thư mục</button><button class="primary-btn">⇧ Tải lên</button></div><div class="card">'+row("▰","Tài liệu cuộc họp","12 mục · cập nhật hôm nay","")+row("▰","Hình ảnh sự kiện","86 mục · 2,1 GB","")+row("PDF","Quy trình giới thiệu khách mời.pdf","2,4 MB · xem trước được","")+row("XLS","Danh sách thành viên.xlsx","820 KB · hôm qua","")+'</div><div class="card"><div class="row between"><div><h3>Dung lượng</h3><p>4,2 GB / 15 GB</p></div><span class="badge cyan">28%</span></div><div class="progress"><span style="width:28%"></span></div></div>',"more","⌕|+");

  if(id==="more") return shell("Thêm","Tài khoản và công cụ",'<div class="card">'+row("NM","Nguyễn Minh","Quản trị viên · IGEN","settings")+'</div><div class="menu-grid">'+[["rankings","★","Bảng xếp hạng","Hoạt động thành viên"],["resources","▰","Tài nguyên","File và Google Drive"],["chat-list","○","Trò chuyện","Tin nhắn và nhóm"],["notifications","♢","Thông báo","8 mục chưa đọc"],["admin-users","U","Quản trị user","Tài khoản và chi nhánh"],["admin-roles","✓","Phân quyền","Vai trò và quyền hạn"],["settings","⚙","Cài đặt","Hồ sơ và hệ thống"],["tablet-command","▣","Bàn điều hành","Tối ưu cho tablet"]].map(function(x){return '<div class="tile" data-go="'+x[0]+'"><i>'+x[1]+'</i><b>'+x[2]+'</b><small>'+x[3]+'</small></div>'}).join("")+'</div>',"more","♢");

  if(id==="admin-users") return shell("Quản trị người dùng","68 tài khoản",'<input class="search" placeholder="⌕  Tìm tên, email, số điện thoại...">'+tabs(["Tất cả","Hoạt động","Đã khóa","Chi nhánh"],"Tất cả")+'<div class="card">'+row("NT","Nguyễn Thành","Manager · Hoạt động","")+row("LH","Lê Hương","User · Hoạt động","")+row("TV","Trần Vũ","Branch owner · Đã khóa","")+'</div><div class="buttons"><button class="secondary-btn">Nhập Excel</button><button class="primary-btn">Thêm tài khoản</button></div>',"more","‹|+");

  if(id==="admin-roles") return shell("Vai trò & phân quyền","Theo doanh nghiệp",'<div class="card"><div class="row between"><div><h3>Manager</h3><p>12 người dùng · 18 quyền</p></div><span class="badge cyan">Mặc định</span></div><p>Dashboard · Cuộc họp · Thành viên · Tài nguyên · Chat</p><button class="secondary-btn" style="width:100%;margin-top:9px">Chỉnh sửa quyền</button></div><div class="card"><h3>Branch Owner</h3><p>4 người dùng · 11 quyền</p><p>Thành viên chi nhánh · Cuộc họp · Chat</p><button class="secondary-btn" style="width:100%;margin-top:9px">Chỉnh sửa quyền</button></div><div class="card"><h3>Ma trận quyền</h3><p>Quyền được nhóm theo module và mở trong màn hình riêng; không dùng bảng cuộn ngang.</p></div>',"more","‹|+");

  if(id==="settings") return shell("Cài đặt","Hồ sơ và hệ thống",'<div class="card">'+row("NM","Nguyễn Minh","admin@igen.vn · Quản trị viên","member-detail")+'</div><div class="card">'+row("◎","Face ID / Vân tay","Chưa thiết lập","biometric")+row("⌁","Đổi mật khẩu","Cập nhật thông tin đăng nhập","")+row("♢","Thông báo","Cuộc họp và chat","notifications")+'</div><div class="card">'+row("ERP","Cấu hình ERP","Module, email và Drive","")+row("DV","Thiết bị đã đăng nhập","1 thiết bị đang hoạt động","")+'</div><button class="secondary-btn" style="color:var(--danger)">Đăng xuất</button>',"more","");

  if(id==="tablet-command") return shell("Bàn điều hành cuộc họp","Họp Chapter tháng 10 · LIVE",flow()+'<div class="tablet-columns"><div class="stack"><div class="card speaker">'+avatar("NH")+'<h3>Nguyễn Hoàng</h3><p>Người đang phát biểu</p></div><div class="card timer"><small>THỜI GIAN CÒN LẠI</small><b>00:42</b><div class="progress"><span style="width:62%"></span></div></div><div class="buttons"><button class="secondary-btn">Tạm dừng</button><button class="primary-btn">Tiếp theo</button></div></div><div class="stack"><div class="card"><div class="section-title"><strong>Danh sách phát biểu</strong><a>Sắp xếp</a></div>'+row("18","Lê Thanh","60 giây","")+row("19","Phạm Anh","45 giây","")+row("20","Đỗ Nam","60 giây","")+row("21","Hoàng Lan","45 giây","")+'</div><div class="buttons"><button class="secondary-btn">Mở slide</button><button class="danger-btn">Kết thúc họp</button></div></div></div>',"meetings","▣|⚙|⋯");
  return content("home");
}

let current="login",deviceType="phone";
function buildList(){var root=document.querySelector("#screen-list"),last="";root.innerHTML=screens.map(function(s){var h=s[0]!==last?'<div class="group">'+s[0]+'</div>':"";last=s[0];return h+'<button class="screen-link" data-screen="'+s[1]+'"><b>'+s[2]+'</b><span>'+s[3]+'</span></button>'}).join("")}
function setDevice(d){deviceType=d;document.querySelector("#device").className="device "+d;document.querySelectorAll("[data-device]").forEach(function(b){b.classList.toggle("active",b.dataset.device===d)})}
function render(id){var s=screens.find(function(x){return x[1]===id})||screens[0];current=s[1];document.querySelector("#screen-title").textContent=s[3];document.querySelector("#screen-note").textContent=s[4];document.querySelector("#app").innerHTML=content(current);document.querySelectorAll(".screen-link").forEach(function(b){b.classList.toggle("active",b.dataset.screen===current)});if(current==="tablet-command")setDevice("tablet")}
document.addEventListener("click",function(e){var s=e.target.closest("[data-screen]"),g=e.target.closest("[data-go]"),d=e.target.closest("[data-device]");if(s)render(s.dataset.screen);if(g)render(g.dataset.go);if(d)setDevice(d.dataset.device)});
buildList();render("login");
